name: nightly

on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * 4

permissions:
  contents: write
  id-token: write
  packages: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    env:
      DOCKER_CLI_EXPERIMENTAL: "enabled"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: arduino/setup-task@v1
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - uses: sigstore/cosign-installer@v3.4.0
      - uses: anchore/sbom-action/download-syft@v0.15.8
      # - uses: cachix/install-nix-action@v25
      #   with:
      #     github_access_token: ${{ secrets.GITHUB_TOKEN }}
      # - name: dockerhub-login
      #   uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v2
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}
      - name: ghcr-login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser-pro
          version: nightly
          args: release --clean --nightly -f .goreleaser-nightly.yaml --timeout 60m
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}
